# Trainig Process

In [4]:
file_path="../data/processed/extracted_skills_only.csv"

import pandas as pd
df_skills=pd.read_csv(file_path)

df_skills.head()

                                    extracted_skills
0  ['forecast', 'data', 'technologies', 'multivar...
1  ['math', 'technologies', 'code', 'distributed'...
2  ['written', 'collaborating', 'recherche', 'd3)...
3  ['data', 'technologies', 'time series data', '...
4  ['data', 'technologies', 'marketing', 'campaig...

In [1]:
file_path="../data/processed/dataset_with_skills.csv"

import pandas as pd
df_skills=pd.read_csv(file_path)

df_skills.head()

,index,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Founded,Type of ownership,Industry,Sector,Competitors,Avg_Sal_K,Size_Avg,Revenue_Avg_Millions,cleaned_description,extracted_skills
0,0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1993,Nonprofit Organization,Insurance Carriers,Insurance,"EmblemHealth, UnitedHealth Group, Aetna",154.0,3000.5,0.0,description senior data scientist responsible ...,"data resources, predictions, analytic methods,..."
1,1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",1968,Company - Public,Research & Development,Business Services,-1,154.0,7500.5,1500.0,secure nation ignite future join top informati...,"Big Data, implementing, data sets, data-focuse..."
2,2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1981,Private Practice / Firm,Consulting,Business Services,-1,154.0,3000.5,300.0,overview analysis group one largest internatio...,"economics, finance, biotech, pharma, energy, e..."
3,3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",154.0,750.5,300.0,job description passion data machine learning ...,"investigates, machine learning, deep learning,..."
4,4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",1998,Company - Private,Advertising & Marketing,Business Services,"Commerce Signals, Cardlytics, Yodlee",154.0,125.5,0.0,data scientist affinity solution marketing clo...,"develop methodology, technologies, insights, m..."